package bot

const (
	cbkLanguage          = "language"
	cbkCheckSubscription = "check_subscription"
	cbkPortfolioPage     = "portfolio_page"
	cbkInstrument        = "instrument"
	cbkInstrumentsPage   = "instruments_page"
	cbkTopUsersPage      = "top_users_page"
	cbkOperationsPage    = "operations_page"
)

const (
	msgDefaultError         = "unknown_error"
	msgNeedSubscribe        = "need_subscribe"
	msgSubscriptionSuccess  = "subscription_success"
	msgSubscriptionFailed   = "subscription_failed"
	msgStart                = "start"
	msgLanguage             = "select_language"
	msgMainMenu             = "main_menu"
	msgInstrumentsList      = "instruments_list"
	msgInstrument           = "instrument"
	msgLastPricePlug        = "last_price_plug"
	msgLastPrice            = "last_price"
	msgInstrumentExit       = "instrument_exit"
	msgFAQ                  = "faq"
	msgTopUsersFirstPage    = "top_users_first_page"
	msgTopUsers             = "top_users"
	msgEnterPromocode       = "enter_promocode"
	msgEnterTicker          = "enter_ticker"
	msgInstrumentNotFound   = "instrument_not_found"
	msgInstrumentFound      = "instrument_found"
	msgEnterCountToBuy      = "enter_count_to_buy"
	msgSuccessfulBuy        = "successful_buy"
	msgEnterCountToSell     = "enter_count_to_sell"
	msgSuccessfulSell       = "successful_sell"
	msgInvalidCount         = "invalid_count"
	msgInsufficientFunds    = "insufficient_funds"
	msgSuccessfulPromocode  = "successful_promocode"
	msgPromocodeAlreadyUsed = "promocode_already_used"
	msgInvalidPromocode     = "invalid_promocode"
	msgOperations           = "operations"
	msgNoOperations         = "no_operations"
	msgOperationBuy         = "operation_buy"
	msgOperationSell        = "operation_sell"
	msgOperationFee         = "operation_fee"
	msgOperationPromocode   = "operation_promocode"
	msgOperationDailyReward = "operation_daily_reward"
	msgPortfolio            = "portfolio"
	msgEmptyPortfolio       = "empty_portfolio"
	msgMarginCall           = "margin_call"
	msgMarginCallWarning    = "margin_call_warning"
	msgClosedExchange       = "closed_exchange"
	msgDailyReward          = "daily_reward"
	msgDailyRewardClaimed   = "daily_reward_claimed"
)

const (
	btnSubscribe           = "button_subscribe"
	btnSubscribed          = "button_subscribed"
	btnLanguage            = "button_language"
	btnPortfolio           = "button_portfolio"
	btnOperations          = "button_operations"
	btnInstrumentsList     = "button_instruments_list"
	btnInstrumentSearch    = "button_instrument_search"
	btnEnterPromocode      = "button_enter_promocode"
	btnFAQ                 = "button_faq"
	btnTopUsers            = "button_top_users"
	btnMainMenu            = "button_main_menu"
	btnNext                = "button_next"
	btnPrevious            = "button_previous"
	btnBuy                 = "button_buy"
	btnSell                = "button_sell"
	btnPortfolioInstrument = "button_portfolio_instrument"
	btnDailyReward         = "button_daily_reward"
)
