package bot

const (
	cbkLanguage          = "language"
	cbkCheckSubscription = "check_subscription"
	cbkPortfolioPage     = "portfolio_page"
	cbkInstrument        = "instrument"
	cbkInstrumentsPage   = "instruments_page"
	cbkTopUsersPage      = "top_users_page"
	cbkOperationsPage    = "operations_page"
)

const (
	msgDefaultError         = "unknown_error"
	msgNeedSubscribe        = "need_subscribe"
	msgSubscriptionSuccess  = "subscription_success"
	msgSubscriptionFailed   = "subscription_failed"
	msgStart                = "start"
	msgLanguage             = "select_language"
	msgMainMenu             = "main_menu"
	msgInstrumentsList      = "instruments_list"
	msgInstrument           = "instrument"
	msgLastPrice            = "last_price"
	msgInstrumentExit       = "instrument_exit"
	msgTopUsersFirstPage    = "top_users_first_page"
	msgTopUsers             = "top_users"
	msgEnterPromocode       = "enter_promocode"
	msgSuccessfulPromocode  = "successful_promocode"
	msgPromocodeAlreadyUsed = "promocode_already_used"
	msgInvalidPromocode     = "invalid_promocode"
	msgOperations           = "operations"
	msgNoOperations         = "no_operations"
	msgOperationBuy         = "operation_buy"
	msgOperationSell        = "operation_sell"
	msgOperationFee         = "operation_fee"
	msgOperationPromocode   = "operation_promocode"
	msgPortfolio            = "portfolio"
	msgEmptyPortfolio       = "empty_portfolio"
	msgMarginCall           = "margin_call"
	msgMarginCallWarning    = "margin_call_warning"
	msgClosedExchange       = "closed_exchange"
)

const (
	btnSubscribe           = "button_subscribe"
	btnSubscribed          = "button_subscribed"
	btnLanguage            = "button_language"
	btnPortfolio           = "button_portfolio"
	btnOperations          = "button_operations"
	btnInstrumentsList     = "button_instruments_list"
	btnInstrumentsSearch   = "button_instruments_search"
	btnEnterPromocode      = "button_enter_promocode"
	btnFAQ                 = "button_faq"
	btnTopUsers            = "button_top_users"
	btnMainMenu            = "button_main_menu"
	btnNextPage            = "button_next_page"
	btnPreviousPage        = "button_previous_page"
	btnBuy                 = "button_buy"
	btnSell                = "button_sell"
	btnPortfolioInstrument = "button_portfolio_instrument"
)
